version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddte-python
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    restart: unless-stopped
    command: python src/main.py

